# 공통설정
server:
  port: 8080


spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;
    username: sa
#    : 스프링부트 2.4부터는 spring.datasource.username=sa 를 꼭 추가해주어야 한다. 그렇지 않으면 오류 발생생
    password:
mybatis:
  type-aliases-package: com.example.demo.dto